### ISSUE TITLE
PRs #1 thru #7

### ISSUE THREAD

**Issue by RossBencina** [Amarok24/The_C_Book__Banahan#8]
Hello Jan,

I found your repository while looking for C89/C90 code that I could use to test a C parser that I'm developing. Thank you for creating it, so far it has helped me find two bugs in my project.

For my project I need C code that compiles cleanly, so I have fixed some issues with the .c files in your repo and made PRs. Most are actual bugs and typos in the code, however #6 and #7 are changes to the .c files so that they are stand-alone .c files rather than just fragments containing statements at top-level. I'm not sure you want to merge those since they would then diverge from the book text.

I'm going to file some issues on the book repo to get the typos fixed in the book.

**Comment by Amarok24** [comment]
Hello Ross and sorry for my _very_ late reaction to this. I was so busy at work and private life that I had zero time for these kind of projects. I have reviewed all of your pull requests and I welcome your effort, all changes make sense and will only help others when learning old-school C :-)
Best regards,
Jan
